[package]
name = "encosmo-client"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
serde = {version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
uuid = {version = "1.11.0", features = ["serde"] }
