[package]
name = "encosmo-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
specs = { version = "0.20.0", features = ["serde", "derive", "uuid"] }
uuid = { version = "1.11.0", features = ["serde"] }
